# Generated by Django 5.1.6 on 2025-02-27 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LU', 'Lunch'), ('DI', 'Dinner')], default='LU', max_length=2)),
                ('meal_date', models.DateField()),
                ('meal_dish_dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_dish_dinner', to='mealcreator.dish')),
                ('meal_dish_lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_dish_lunch', to='mealcreator.dish')),
            ],
        ),
    ]
